# Generated by Django 5.0.6 on 2024-06-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_category_options_blogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': 'Blogs'},
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog_body',
        ),
    ]
