# Generated by Django 5.2.4 on 2025-07-29 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('subscribe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogapp.subscribe')),
                ('subject', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
            bases=('blogapp.subscribe',),
        ),
    ]
